### ISSUE TITLE
Great plugin！thank author for it！ 

### ISSUE THREAD

**Issue by sdbds** [adnanc/HDT.Plugins.MetaDetector#1]
i test it and it  works very well。
i like save deck function！
one suggestion：hope show deck name instead of hero name like shaman and warrior with each deck。

**Comment by AdnanC** [comment]
Thanks for trying it out. Let me know if you encounter any problems.

I wanted to add the deck names, but since I get most of the decks from sites like manacrystals, hearthpwn etc., the names are really long and took up a lot of space. I will consider adding an option to show / hide deck names.

**Comment by sdbds** [comment]
hope to add detect some card revealed by which in TGT can reveal both card like king's Elekk。

**Comment by AdnanC** [comment]
yes, already working on that. hopefully will be able to push that out with the next update
