### ISSUE TITLE
can i help to localize http://metastats.net？

### ISSUE THREAD

**Issue by sdbds** [adnanc/HDT.Plugins.MetaDetector#11]
i had promoted this to my Chinese BBS，so there are many Chinese users。
can i localize metastats.net？
i want to promote more.

**Comment by AdnanC** [comment]
really appreciate any help with promoting. More people means better picture of the meta. I haven't considered localizing the site but that is a nice idea. i will get the framework ready and when i need help with translating I will let you know.
