### ISSUE TITLE
Nothing happens?

### ISSUE THREAD

**Issue by RedHatter** [adnanc/HDT.Plugins.MetaDetector#14]
No matter what I do the Meta Detector list stays blank. Here is the log.
[meta_log.txt](https://github.com/AdnanC/HDT.Plugins.MetaDetector/files/887001/meta_log.txt)

**Comment by AdnanC** [comment]
Looks like the deck file might have been corrupted during upload. Can you delete "metaDecks.xml" file from the MetaDetector folder and try again. Let me know if you still get a blank list.

**Comment by RedHatter** [comment]
That worked. Thank you!
