### ISSUE TITLE
0.06 cant download meta deck data

### ISSUE THREAD

**Issue by sdbds** [adnanc/HDT.Plugins.MetaDetector#3]
13:14:30|Info|MetaDetector.MetaDetector >> Meta Detector Initialized
13:14:30|Info|MetaDetectorPlugin.OnLoad >> Plugin Load Successful
13:16:29|Info|MetaDetectorPlugin.OnUnload >> Plugin Unload Successful

just this。

**Comment by AdnanC** [comment]
The plugin now downloads the latest deck file when a new game starts instead of onload. The onload was causing a delay and some people kept enabling/disabling the plugin.

Let me know if you still have any issues after starting a new game.

**Comment by sdbds** [comment]
it works well after play a game。
i dont know meta rank how to    calculate，why they are 0.XX？

**Comment by AdnanC** [comment]
don't worry about the meta rank. that's just something to help predict the deck.
