### ISSUE TITLE
Removed plugin from HDT wiki.

### ISSUE THREAD

**Issue by azeier** [adnanc/HDT.Plugins.MetaDetector#8]
Hey,

I removed this plugin from the official list again, sorry.
Opponent deck detection/prediction is not something we want to support.

Edit: Looks like you didn't add it to the wiki yourself. So this is more of an fyi then :).

**Comment by AdnanC** [comment]
Yup wasn't me :) 

I am working on separating the stats part into it's own plugin. I might add that to the wiki.
