### ISSUE TITLE
0.08 cant download meta deck data

### ISSUE THREAD

**Issue by sdbds** [adnanc/HDT.Plugins.MetaDetector#9]
if i first use it ，it cant check new version and download meta file。
if i have old data，i can update them with new file like mega.xml。

**Comment by AdnanC** [comment]
The plugin checks for new version every 2 days. If there is a new file it will download. You can force it to download by renaming metaDecks.xml file in the plugin folder before starting HDT. Let me know if that works for you.

**Comment by sdbds** [comment]
no，i mean if i first use it，it doesnt download meta file，just
log folder
cardStats.xml
and metaConfig.xml
maybe i need to create a txt and rename it with metaDecks.xml？

here is log
12:22:15|Info|MetaDetector.MetaDetector >> Meta Detector Initialized
12:22:15|Info|MetaDetectorPlugin.OnLoad >> Plugin Load Successful
12:23:01|Info|MetaDetector.GameStart >> Game Mode: Practice
12:23:01|Info|MetaDetector.GameStart >> Game Format: Wild
12:23:01|Info|MetaDetector.GameStart >> Region: CHINA
12:23:01|Info|MetaDetector.GameStart >> Mode: ADVENTURE
12:23:01|Info|MetaDetector.GameStart >> New Game Started. Waiting for opponent to play cards.
12:23:03|Info|MetaDetector.updatePlayerHandCards >> Turn 0: Player Draws 野蛮咆哮
12:23:03|Info|MetaDetector.updatePlayerHandCards >> Turn 0: Player Draws 奥妮克希亚
12:23:03|Info|MetaDetector.updatePlayerHandCards >> Turn 0: Player Draws 寒光智者
12:23:29|Info|MetaDetector.updatePlayerHandCards >> Turn 0: Player Draws 达纳苏斯豹骑士
12:23:29|Info|MetaDetector.PlayerMulligan >> Player Mulliganed Onyxia
12:23:29|Info|MetaDetector.updatePlayerHandCards >> Turn 0: Player Draws 活体根须
12:23:29|Info|MetaDetector.PlayerMulligan >> Player Mulliganed Coldlight Oracle

by the way，another metastat should i need to download if i have this metadetector？

**Comment by AdnanC** [comment]
If you already have MetaDetector Plugin, you don't need to install
MetaStats. Actually that might cause conflict. I will add a check to make
sure there is a warning if both plugins are enabled.

Do you currently have both enabled? If so, try disabling MetaStats and only
use MetaDetector.

**Comment by AdnanC** [comment]
I was able to find the problem. It should be fixed in the latest release. Let me know if it works for you now.

**Comment by sdbds** [comment]
it works well now。

**Comment by AdnanC** [comment]
good to hear
